interface Fixture {
    month: string
    date: string
    time: string
    homeTeam: string
    awayTeam: string
    leagueName: string
    LeagueLogo: string
    homeTeamLogo: string
    awayTeamLogo: string
    stadium: string
}
interface Players {
    firstName: string,
    lastName: string,
    playerType: string,
    nationality: string,
    height: string,
    color: string,
    weight: string
    shirtNumber: string
    photo: string
}

interface Team {
    goalKeepers: Players[],
    defenders: Players[],
    midFielders: Players[],
    attackers: Players[]
}
export interface Article {
    id: number
    category: 'interviews' | 'news'
    title: string
    description: string
    image: string
    time: string
    featured?: boolean
}
export const players: Team[] = [
    {
        goalKeepers: [
            //     {
            //     firstName: 'Raya',
            //     lastName: 'David',
            //     playerType: 'GoalKeeper',
            //     nationality: 'Spain',
            //     height: '5.7 metres',
            //     color: 'yellow',
            //     weight: '70kg',
            //     shirtNumber: '13',
            //     photo: '/public/assets/images/sakaHeadshot.png'
            // },
            {
                firstName: 'james',
                lastName: 'Aderogba',
                playerType: 'GoalKeeper',
                nationality: 'Nigeria',
                height: '6metres',
                color: 'black',
                weight: '72kg',
                shirtNumber: '13',
                photo: '/public/assets/images/player.png'
            },
            {
                firstName: 'james',
                lastName: 'Aderogba',
                playerType: 'GoalKeeper',
                nationality: 'Nigeria',
                height: '6metres',
                color: 'black',
                weight: '72kg',
                shirtNumber: '13',
                photo: '/public/assets/images/player.png'
            },
            {
                firstName: 'james',
                lastName: 'Aderogba',
                playerType: 'GoalKeeper',
                nationality: 'Nigeria',
                height: '6metres',
                color: 'black',
                weight: '72kg',
                shirtNumber: '13',
                photo: '/public/assets/images/player.png'
            },
            // {
            //     firstName: 'Raya',
            //     lastName: 'David',
            //     playerType: 'GoalKeeper',
            //     nationality: 'Spain',
            //     height: '5.7 metres',
            //     color: 'yellow',
            //     weight: '70kg',
            //     shirtNumber: '13',
            //     photo: '/public/assets/images/sakaHeadshot.png'
            // }
        ],
        defenders: [{
            firstName: 'william',
            lastName: 'saliba',
            playerType: 'Defender',
            nationality: 'france',
            height: '6metres',
            color: 'yellow',
            weight: '75kg',
            shirtNumber: '13',
            photo: '/public/assets/images/player.png'
        },
        // {
        //     firstName: 'Gabriel',
        //     lastName: 'malgaheas',
        //     playerType: 'Defender',
        //     nationality: 'brasil',
        //     height: '6metres',
        //     color: 'yellow',
        //     weight: '77kg',
        //     shirtNumber: '13',
        //     photo: '/public/assets/images/sakaHeadshot.png'
        // },
        {
            firstName: 'Ben ',
            lastName: 'White',
            playerType: 'Defender',
            nationality: 'England',
            height: '5.8metres',
            color: 'white',
            weight: '71kg',
            shirtNumber: '13',
            photo: '/public/assets/images/player.png'
        },
        {
            firstName: 'Ben ',
            lastName: 'White',
            playerType: 'Defender',
            nationality: 'England',
            height: '5.8metres',
            color: 'white',
            weight: '71kg',
            shirtNumber: '13',
            photo: '/public/assets/images/player.png'
        }],
        midFielders: [
            //     {
            //     firstName: 'martin ',
            //     lastName: 'odegard',
            //     playerType: 'midfielder',
            //     nationality: 'Norway',
            //     height: '5.6metres',
            //     color: 'white',
            //     weight: '70kg',
            //     shirtNumber: '13',
            //     photo: '/public/assets/images/sakaHeadshot.png'
            // },
            {
                firstName: 'rice',
                lastName: 'declan ',
                playerType: 'midfielder',
                nationality: 'england',
                height: '6meters',
                color: 'white',
                weight: '71kg',
                shirtNumber: '13',
                photo: '/public/assets/images/player.png'
            },
            {
                firstName: 'rice',
                lastName: 'declan ',
                playerType: 'midfielder',
                nationality: 'england',
                height: '6meters',
                color: 'white',
                weight: '71kg',
                shirtNumber: '13',
                photo: '/public/assets/images/player.png'
            },
            {
                firstName: 'rice',
                lastName: 'declan ',
                playerType: 'midfielder',
                nationality: 'england',
                height: '6meters',
                color: 'white',
                weight: '71kg',
                shirtNumber: '13',
                photo: '/public/assets/images/player.png'
            }
            // {
            //     firstName: 'eberechi',
            //     lastName: 'eze',
            //     playerType: 'midfielder',
            //     nationality: 'england',
            //     height: '5.7meteres',
            //     color: 'black',
            //     weight: '70kg',
            //     shirtNumber: '13',
            //     photo: '/public/assets/images/sakaHeadshot.png'
            // }
        ],
        attackers: [{
            firstName: 'Bukayo',
            lastName: 'saka',
            playerType: 'Attacker',
            nationality: 'england',
            height: '5.8meters',
            color: 'black',
            weight: '70kg',
            shirtNumber: '13',
            photo: '/public/assets/images/player.png'
        },
        // {
        //     firstName: 'victor ',
        //     lastName: 'gyokeres',
        //     playerType: 'Attacker',
        //     nationality: 'sweden',
        //     height: '6metres',
        //     color: 'white',
        //     weight: '75kg',
        //     shirtNumber: '13',
        //     photo: '/public/assets/images/sakaHeadshot.png'
        // },
        {
            firstName: 'rice',
            lastName: 'declan ',
            playerType: 'midfielder',
            nationality: 'england',
            height: '6meters',
            color: 'white',
            weight: '71kg',
            shirtNumber: '13',
            photo: '/public/assets/images/player.png'
        },
        {
            firstName: 'trossard',
            lastName: 'leonard',
            playerType: 'attacker',
            nationality: 'belgium',
            height: '5.8metres',
            color: 'white',
            weight: '73kg',
            shirtNumber: '13',
            photo: '/public/assets/images/player.png'
        }]
    },
]
export const LeagueTableRow = [
    {
        pos: 1,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 2,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 3,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 4,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 5,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 6,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 7,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 8,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 9,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 10,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 11,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 12,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 13,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 14,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 15,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 16,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 17,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 18,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 19,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },
    {
        pos: 20,
        team: 'JOFSA King',
        teamLogo: '/assets/images/jofsa.png',
        P: 11,
        W: 8,
        D: 2,
        L: 1,
        GF: 20,
        GA: 5,
        GD: 15,
        difference: 15,
        Pts: 15,
    },

]
export const fixtures: Fixture[] = [
    {
        month: 'November',
        date: 'SUN, 05 NOV, 16:15 WAT',
        time: '15:00',
        homeTeam: 'Kwara united',
        awayTeam: 'JOFSA King',
        leagueName: 'Nigeria Premier League',
        LeagueLogo: '/assets/images/LeagueLogo.png',
        homeTeamLogo: '/assets/images/HomeTeam/Logo.png',
        awayTeamLogo: '/assets/images/AwayTeam/Logo.png',
        stadium: 'Moshood abiola stadium',
    },
    {
        month: 'December',
        date: 'SUN, 05 NOV, 16:15 WAT',
        time: '18:00',
        homeTeam: 'Kwara united',
        awayTeam: 'JOFSA King',
        leagueName: 'Nigeria Premier League',
        LeagueLogo: '/assets/images/LeagueLogo.png',
        homeTeamLogo: '/assets/images/HomeTeam/Logo.png',
        awayTeamLogo: '/assets/images/AwayTeam/Logo.png',
        stadium: 'Moshood abiola stadium',
    },
    {
        month: 'January',
        date: 'SUN, 05 NOV, 16:15 WAT',
        time: '18:00',
        homeTeam: 'Kwara united',
        awayTeam: 'JOFSA King',
        leagueName: 'Nigeria Premier League',
        LeagueLogo: '/assets/images/LeagueLogo.png',
        homeTeamLogo: '/assets/images/HomeTeam/Logo.png',
        awayTeamLogo: '/assets/images/AwayTeam/Logo.png',
        stadium: 'Moshood abiola stadium',
    },
]
export const matches = [{
    month: 'November',
    date: 'SUN, 05 NOV, 16:15 WAT',
    time: '15:00',
    homeTeam: 'Kwara united',
    awayTeam: 'JOFSA King',
    leagueName: 'Nigeria Premier League',
    LeagueLogo: '/assets/images/LeagueLogo.png',
    homeTeamLogo: '/assets/images/HomeTeam/Logo.png',
    awayTeamLogo: '/assets/images/AwayTeam/Logo.png',
    stadium: 'Moshood abiola stadium',
},
{
    month: 'December',
    date: 'SUN, 05 NOV, 16:15 WAT',
    time: '18:00',
    homeTeam: 'Kwara united',
    awayTeam: 'JOFSA King',
    leagueName: 'Nigeria Premier League',
    LeagueLogo: '/assets/images/LeagueLogo.png',
    homeTeamLogo: '/assets/images/HomeTeam/Logo.png',
    awayTeamLogo: '/assets/images/AwayTeam/Logo.png',
    stadium: 'Moshood abiola stadium',
},
{
    month: 'January',
    date: 'SUN, 05 NOV, 16:15 WAT',
    time: '18:00',
    homeTeam: 'Kwara united',
    awayTeam: 'JOFSA King',
    leagueName: 'Nigeria Premier League',
    LeagueLogo: '/assets/images/LeagueLogo.png',
    homeTeamLogo: '/assets/images/HomeTeam/Logo.png',
    awayTeamLogo: '/assets/images/AwayTeam/Logo.png',
    stadium: 'Moshood abiola stadium',
},]
export const articles: Article[] = [
    {
        id: 1,
        category: 'interviews',
        title: 'Strong record of player development and community engagement',
        description: 'Lorem ipsum dolor sit amet consectetur. Ut sit tristique neque posuere cum. Sit dolor',
        image: 'articleImage.png',
        time: '2 HOURS AGO',
        featured: true
    },
    {
        id: 2,
        category: 'interviews',
        title: 'Strong record of player development and community engagement',
        description: 'Lorem ipsum dolor sit amet consectetur. Ut sit tristique neque posuere cum. Sit dolor',
        image: 'training.png',
        time: '2 HOURS AGO'
    },
    {
        id: 3,
        category: 'interviews',
        title: 'Strong record of player development and community engagement',
        description: 'Lorem ipsum dolor sit amet consectetur. Ut sit tristique neque posuere cum. Sit dolor',
        image: 'training.png',
        time: '2 HOURS AGO'
    },
    {
        id: 4,
        category: 'news',
        title: 'Strong record of player development and community engagement',
        description: 'Lorem ipsum dolor sit amet consectetur. Ut sit tristique neque posuere cum. Sit dolor',
        image: 'playingball.png',
        time: '2 HOURS AGO'
    },
    {
        id: 5,
        category: 'interviews',
        title: 'Strong record of player development and community engagement',
        description: 'Lorem ipsum dolor sit amet consectetur. Ut sit tristique neque posuere cum. Sit dolor',
        image: 'training.png',
        time: '2 HOURS AGO'
    }
]